server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=false

# To improve the performance during development.
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example.specdriven

# H2 Database
spring.datasource.url=jdbc:h2:mem:forgedb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
